# Plugin made by Faxu

stats:
  # Vanilla Default = 20
  default-constitution: 20   # Remember 2 points of life = 1 Heart
  dexterity-affects-snowball: true
  dexterity-affects-egg: true

leveling:
  max-level: 10
  multiplier-base: 50 #Base level needed for increase level race
  multiplier-level: 25 #This amount will be multiplied by the number of current levels

racial-abilities:
  civilization-walker:
    constitution: 1
    defense: 1
    strength: 1
    dexterity: 1
    intelligence: 1
    wisdom: 1
    luck: 1
    charisma: 1
  forest-dweller:
    constitution: 0
    defense: 0
    strength: 0
    dexterity: 4
    intelligence: 2
    wisdom: 2
    luck: 0
    charisma: 0
  cave-and-cliffs-life:
    constitution: 2
    defense: 0
    strength: 1
    dexterity: 0
    intelligence: 0
    wisdom: 2
    luck: 0
    charisma: 3
  path-of-the-reaver:
    constitution: 4
    defense: 2
    strength: 2
    dexterity: 0
    intelligence: 0
    wisdom: 0
    luck: 0
    charisma: 0

messages:
  sql-error: "&cSQL error, please report to administrator."
  no-perms: "&cYou don't have permissions for this."
  no-arguments: "&cThis command need arguments. Please read the documentation."
  invalid-player: "&cInvalid player."
  sufficient-willpower: "&cYou don't have sufficient willpower."
  choose-new-race: "&6You choose a new race."
  already-have-race: "&eYou already have this race. Choose another!"
  no-have-level: "&cYou don't have sufficient levels"
  level-up: "&aLevel Up!"
  no-have-points: "&cYou don't have Stats Points for use"
  need-race: "&6You are a simple Soul. First choose one race."

  commands:
    need-player: "&cYou need provide a player name."
    need-stat: "&cYou need provide a name of stat."
    need-number: "You need provide a number."

  abilities:
    civilization-enter: "&aYou have entered a biome where civilization may exists..."
    civilization-left: "&eThe possibilities of civilization have been left behind.."
    forest-enter: "&aYou entered a forest..."
    forest-left: "&eYou came out of a forest..."
    cave-or-cliffs-enter: "&aHave you arrived at a cave... or a mountain?"
    cave-or-cliffs-left: "&eYou have left your ancestral lands behind..."
    path-reaver-enter: "&aHave these lands already been looted?"
    path-reaver-left: "&eApparently... there was nothing interesting there"