name: LostWorld
version: '${project.version}'
main: faxu.lost_world.lostworld.LostWorld
api-version: 1.20
author: Faxu
description: Races, stats, classes and skills!
commands:
  lostworld:
    description: Main command of plugin LostWorld.
    usage: /lostworld
permissions:
  seestats:
    description: Show stats of selected player.
    default: true
  setstat:
    description: Sets the stat amount of the selected player.
    default: op
  updatestat:
    description: Increase the stat of the selected player.
    default: op
  races:
    description: Shows existing breeds for you to choose one.
    default: true